// @ts-nocheck
// GENERATED by `cargo run --bin export-bindings` in src-tauri/. Do not edit.
// Source of truth: src-tauri/src/ipc/. Re-run after changing any command or event.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	dockGetState: () => __TAURI_INVOKE<DockState>("dock_get_state"),
	dockShow: (req: DockShowRequest) => __TAURI_INVOKE<DockState>("dock_show", { req }),
	/**
	 *  Called by the UI once its exit animation has completed, whether the hide
	 *  started in the UI (Esc) or in Rust (`dock_state_changed { open: false }`).
	 */
	dockHide: (req: DockHideRequest) => __TAURI_INVOKE<DockState>("dock_hide", { req }),
	dockPin: (req: DockPinRequest) => __TAURI_INVOKE<DockState>("dock_pin", { req }),
	dockSetMode: (req: DockSetModeRequest) => __TAURI_INVOKE<DockState>("dock_set_mode", { req }),
	/**  The user clicked the composer (or another focus target): Passive -> Active. */
	dockActivate: () => __TAURI_INVOKE<void>("dock_activate"),
	dockOpenSettings: () => __TAURI_INVOKE<void>("dock_open_settings"),
	anchorSetY: (req: AnchorSetYRequest) => __TAURI_INVOKE<AnchorY>("anchor_set_y", { req }),
	anchorHide: () => __TAURI_INVOKE<DockState>("anchor_hide"),
	anchorShow: () => __TAURI_INVOKE<DockState>("anchor_show"),
	anchorMenuPopup: () => __TAURI_INVOKE<null>("anchor_menu_popup"),
	anchorSetExpanded: (req: AnchorSetExpandedRequest) => __TAURI_INVOKE<void>("anchor_set_expanded", { req }),
	pauseSet: (req: PauseSetRequest) => __TAURI_INVOKE<DockState>("pause_set", { req }),
	appQuit: () => __TAURI_INVOKE<void>("app_quit"),
	authSignIn: () => __TAURI_INVOKE<Session_Serialize>("auth_sign_in"),
	authSignOut: () => __TAURI_INVOKE<null>("auth_sign_out"),
	authGetSession: () => __TAURI_INVOKE<Session_Serialize>("auth_get_session"),
	askSubmit: (req: AskSubmitRequest_Deserialize) => __TAURI_INVOKE<AskSubmitResult>("ask_submit", { req }),
	askCancel: (req: AskCancelRequest) => __TAURI_INVOKE<null>("ask_cancel", { req }),
	attentionList: () => __TAURI_INVOKE<unknown[]>("attention_list"),
	attentionDecide: (req: AttentionDecision_Deserialize) => __TAURI_INVOKE<AttentionDecideResult>("attention_decide", { req }),
	ledgerQuery: (req: LedgerQuery_Deserialize) => __TAURI_INVOKE<LedgerPage_Serialize>("ledger_query", { req }),
	journeyGet: (req: JourneyGetRequest) => __TAURI_INVOKE<unknown>("journey_get", { req }),
	settingsGet: () => __TAURI_INVOKE<Settings>("settings_get"),
	settingsSet: (req: Settings) => __TAURI_INVOKE<Settings>("settings_set", { req }),
	monitorsList: () => __TAURI_INVOKE<MonitorInfo[]>("monitors_list"),
	/**  Opens https links (and configured hosts) in the system browser. Never file:, javascript:, or custom schemes. */
	openExternal: (req: OpenExternalRequest) => __TAURI_INVOKE<null>("open_external", { req }),
	/**  UI telemetry breadcrumbs; forwarded to the trace pipeline (log-only until Sentry/OTel land). */
	telemetryEvent: (req: TelemetryEventRequest) => __TAURI_INVOKE<void>("telemetry_event", { req }),
};

/** Events */
export const events = {
	attentionExpired: makeEvent<AttentionExpired>("attention_expired"),
	attentionNew: makeEvent<AttentionNew>("attention_new"),
	attentionResolved: makeEvent<AttentionResolved>("attention_resolved"),
	connectivityChanged: makeEvent<ConnectivityChanged>("connectivity_changed"),
	dockStateChanged: makeEvent<DockStateChanged>("dock_state_changed"),
	ledgerAppended: makeEvent<LedgerAppended>("ledger_appended"),
	presentationChanged: makeEvent<PresentationChanged>("presentation_changed"),
	sessionChanged: makeEvent<SessionChanged_Deserialize>("session_changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings_changed"),
	settingsRequested: makeEvent<SettingsRequested>("settings_requested"),
	taskState: makeEvent<TaskState_Deserialize>("task_state"),
	themeChanged: makeEvent<ThemeChanged>("theme_changed"),
};

/* Types */
export type AnchorSetExpandedRequest = {
	expanded: boolean,
};

export type AnchorSetYRequest = {
	/**  Pill top edge in logical (DIP) screen coordinates. */
	yLogical: number,
	/**  Persist the position (pointer released). */
	commit: boolean,
};

export type AnchorY = {
	yLogical: number,
};

export type AskCancelRequest = {
	taskId: string,
};

export type AskSubmitRequest = AskSubmitRequest_Serialize | AskSubmitRequest_Deserialize;

export type AskSubmitRequest_Deserialize = {
	text: string,
	journeyId?: string | null,
	clientRequestId: string,
};

export type AskSubmitRequest_Serialize = {
	text: string,
	journeyId?: string | null,
	clientRequestId: string,
};

export type AskSubmitResult = {
	journeyId: string,
	taskId: string,
};

export type AttentionDecideResult = {
	accepted: boolean,
};

/**  `contracts/schemas/attention.ts` `AttentionDecision` (strict object). */
export type AttentionDecision = AttentionDecision_Serialize | AttentionDecision_Deserialize;

/**  `contracts/schemas/attention.ts` `AttentionDecision` (strict object). */
export type AttentionDecision_Deserialize = {
	attentionId: string,
	decision: string,
	freeText?: string | null,
	decidedAt: string,
	idempotencyKey: string,
};

/**  `contracts/schemas/attention.ts` `AttentionDecision` (strict object). */
export type AttentionDecision_Serialize = {
	attentionId: string,
	decision: string,
	freeText?: string | null,
	decidedAt: string,
	idempotencyKey: string,
};

export type AttentionExpired = AttentionRefEvent;

export type AttentionNew = AttentionNewEvent;

export type AttentionNewEvent = {
	eventId: string,
	item: unknown,
};

export type AttentionRefEvent = {
	eventId: string,
	attentionId: string,
};

export type AttentionResolved = AttentionRefEvent;

export type Connectivity = {
	state: ConnectivityState,
	sinceEpochMs: number,
};

export type ConnectivityChanged = Connectivity;

export type ConnectivityState = "online" | "reconnecting" | "offline";

export type DockHideRequest = {
	reason: HideReason,
};

export type DockPinRequest = {
	pinned: boolean,
};

export type DockSetModeRequest = {
	mode: Mode,
};

export type DockShowRequest = {
	mode?: Mode | null,
	reason: ShowReason,
};

export type DockState = {
	open: boolean,
	mode: Mode,
	pinned: boolean,
	/**  Panel has keyboard focus (Passive -> Active). */
	active: boolean,
	paused: boolean,
	pausedUntilEpochMs: number | null,
	pillVisible: boolean,
};

export type DockStateChanged = DockState;

export type Edge = "right" | "left";

/**  Empty payload for `settings_requested`. */
export type Empty = Record<string, never>;

export type HideReason = "esc" | "outside" | "grace" | "ui" | "lock" | "pill";

export type IpcError = IpcError_Serialize | IpcError_Deserialize;

export type IpcErrorCode = "unauthenticated" | "offline" | "timeout" | "rejected" | "conflict" | "invalid" | "internal";

export type IpcError_Deserialize = {
	code: IpcErrorCode,
	message: string,
	retryable: boolean,
	correlationId?: string | null,
};

export type IpcError_Serialize = {
	code: IpcErrorCode,
	message: string,
	retryable: boolean,
	correlationId?: string | null,
};

export type JourneyGetRequest = {
	journeyId: string,
};

export type LedgerAppended = LedgerAppendedEvent;

export type LedgerAppendedEvent = {
	eventId: string,
	row: unknown,
};

export type LedgerFilters = {
	platforms?: string[],
	statuses?: string[],
	scope?: string,
};

export type LedgerPage = LedgerPage_Serialize | LedgerPage_Deserialize;

export type LedgerPage_Deserialize = {
	rows: unknown[],
	nextCursor?: string | null,
};

export type LedgerPage_Serialize = {
	rows: unknown[],
	nextCursor?: string | null,
};

export type LedgerQuery = LedgerQuery_Serialize | LedgerQuery_Deserialize;

export type LedgerQuery_Deserialize = {
	filters: LedgerFilters,
	cursor?: string | null,
	limit?: number | null,
};

export type LedgerQuery_Serialize = {
	filters: LedgerFilters,
	cursor?: string | null,
	limit?: number | null,
};

export type Mode = "ask" | "attention" | "recent";

export type MonitorInfo = {
	name: string,
	primary: boolean,
	scaleFactor: number,
};

export type MotionPreference = "system" | "reduced";

export type OpenExternalRequest = {
	url: string,
};

export type PauseSetRequest = {
	untilEpochMs: number | null,
};

export type PresentationChanged = PresentationChangedPayload;

export type PresentationChangedPayload = {
	presenting: boolean,
};

/**  What the webview may know about the user. Never carries tokens (ADR-002 §7). */
export type Session = Session_Serialize | Session_Deserialize;

export type SessionChanged = SessionChanged_Serialize | SessionChanged_Deserialize;

export type SessionChanged_Deserialize = Session_Deserialize;

export type SessionChanged_Serialize = Session_Serialize;

export type SessionState = "signed_out" | "signing_in" | "signed_in";

/**  What the webview may know about the user. Never carries tokens (ADR-002 §7). */
export type Session_Deserialize = {
	state: SessionState,
	userId?: string | null,
	displayName?: string | null,
	upn?: string | null,
	tenantId?: string | null,
	expiresAt?: string | null,
	reason?: SignOutReason | null,
};

/**  What the webview may know about the user. Never carries tokens (ADR-002 §7). */
export type Session_Serialize = {
	state: SessionState,
	userId?: string | null,
	displayName?: string | null,
	upn?: string | null,
	tenantId?: string | null,
	expiresAt?: string | null,
	reason?: SignOutReason | null,
};

export type Settings = {
	shortcutOpen?: string,
	shortcutPin?: string,
	/**  Monitor name; `None` = primary. */
	display?: string | null,
	edge?: Edge,
	pillVisible?: boolean,
	autostart?: boolean,
	pinByDefault?: boolean,
	excludeFromCapture?: boolean,
	theme?: ThemePreference,
	motion?: MotionPreference,
	vibrancy?: boolean,
};

/**
 *  Settings were saved (from the sheet or a menu). Every window mirrors them,
 *  so the pill picks up a theme change made in the panel.
 */
export type SettingsChanged = Settings;

/**  The tray asked for Settings; the panel opens its sheet. */
export type SettingsRequested = Empty;

export type ShowReason = "pill" | "hotkey" | "tray" | "attention" | "toast";

export type SignOutReason = "user" | "expired" | "revoked" | "forced" | "error";

export type SystemTheme = "light" | "dark";

export type TaskState = TaskState_Serialize | TaskState_Deserialize;

export type TaskStateEvent = TaskStateEvent_Serialize | TaskStateEvent_Deserialize;

export type TaskStateEvent_Deserialize = {
	eventId: string,
	journeyId: string,
	taskId: string,
	/**  A2A state: submitted | working | input-required | auth-required | completed | failed | rejected | canceled. */
	state: string,
	agentId?: string | null,
	cards?: unknown[] | null,
	message?: string | null,
};

export type TaskStateEvent_Serialize = {
	eventId: string,
	journeyId: string,
	taskId: string,
	/**  A2A state: submitted | working | input-required | auth-required | completed | failed | rejected | canceled. */
	state: string,
	agentId?: string | null,
	cards?: unknown[] | null,
	message?: string | null,
};

export type TaskState_Deserialize = TaskStateEvent_Deserialize;

export type TaskState_Serialize = TaskStateEvent_Serialize;

export type TelemetryEventRequest = {
	name: string,
	props?: unknown,
};

export type ThemeChanged = ThemeChangedPayload;

export type ThemeChangedPayload = {
	system: SystemTheme,
};

export type ThemePreference = "system" | "light" | "dark";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

