import { z } from 'zod';
import { commands, events } from '@contracts/bindings/bindings';
import { AttentionDecideResult, AttentionItem } from '@contracts/schemas/attention';
import type { AttentionDecision } from '@contracts/schemas/attention';
import { DockState } from '@contracts/schemas/dock';
import type { Mode } from '@contracts/schemas/dock';
import { AskSubmitResult } from '@contracts/schemas/ipc';
import type { AskSubmitRequest, IpcError } from '@contracts/schemas/ipc';
import { JourneyThread } from '@contracts/schemas/journey';
import { LedgerPage } from '@contracts/schemas/ledger';
import type { LedgerQuery } from '@contracts/schemas/ledger';
import { Session } from '@contracts/schemas/session';
import { MonitorInfo, Settings } from '@contracts/schemas/settings';
import { log } from '@/lib/log';
import type { AdapterEventName, DockHideRequest, DockShowRequest, LoopAdapter } from './adapter';
import { EventHub } from './events';

/**
 * Dock adapter. Talks to the Rust shell through the `tauri-specta` bindings in
 * `contracts/bindings/bindings.ts` (generated by `cargo run --bin
 * export-bindings`), so a renamed command or argument fails `tsc` here rather
 * than at runtime. Every result is still validated with the contract schemas:
 * the bindings describe shapes, Zod enforces them.
 *
 * The only file in src/ that may import `@tauri-apps/*` (via the bindings).
 */

/** Generated event key for each adapter event name. */
const EVENT_KEYS: Record<AdapterEventName, keyof typeof events> = {
  dock_state_changed: 'dockStateChanged',
  theme_changed: 'themeChanged',
  session_changed: 'sessionChanged',
  connectivity_changed: 'connectivityChanged',
  task_state: 'taskState',
  attention_new: 'attentionNew',
  attention_resolved: 'attentionResolved',
  attention_expired: 'attentionExpired',
  ledger_appended: 'ledgerAppended',
  presentation_changed: 'presentationChanged',
  settings_requested: 'settingsRequested',
  settings_changed: 'settingsChanged',
};

async function call<T>(name: string, run: () => Promise<unknown>, schema?: z.ZodType<T>): Promise<T> {
  let result: unknown;
  try {
    result = await run();
  } catch (err) {
    // Rust throws `IpcError` as a serialised object; anything else is internal.
    const maybe = err as Partial<IpcError> | string;
    if (typeof maybe === 'object' && maybe && typeof maybe.code === 'string') throw maybe as IpcError;
    throw <IpcError>{ code: 'internal', message: String(err), retryable: false };
  }
  if (!schema) return result as T;
  const parsed = schema.safeParse(result);
  if (!parsed.success) {
    log.warn(`invalid result from ${name}`, { issues: z.prettifyError(parsed.error) });
    throw <IpcError>{ code: 'invalid', message: `Invalid result from ${name}`, retryable: false };
  }
  return parsed.data;
}

export class TauriAdapter implements LoopAdapter {
  readonly kind = 'tauri' as const;
  private hub = new EventHub();

  constructor() {
    for (const [name, key] of Object.entries(EVENT_KEYS) as [AdapterEventName, keyof typeof events][]) {
      void events[key].listen((e) => this.hub.emitRaw(name, e.payload));
    }
  }

  dockGetState(): Promise<DockState> {
    return call('dock_get_state', () => commands.dockGetState(), DockState);
  }
  dockShow(req: DockShowRequest): Promise<DockState> {
    return call('dock_show', () => commands.dockShow(req), DockState);
  }
  dockHide(req: DockHideRequest): Promise<DockState> {
    return call('dock_hide', () => commands.dockHide(req), DockState);
  }
  dockPin(pinned: boolean): Promise<DockState> {
    return call('dock_pin', () => commands.dockPin({ pinned }), DockState);
  }
  dockSetMode(mode: Mode): Promise<DockState> {
    return call('dock_set_mode', () => commands.dockSetMode({ mode }), DockState);
  }
  dockActivate(): Promise<void> {
    return call('dock_activate', () => commands.dockActivate());
  }
  anchorSetY(yLogical: number, commit: boolean): Promise<{ yLogical: number }> {
    return call(
      'anchor_set_y',
      () => commands.anchorSetY({ yLogical, commit }),
      z.object({ yLogical: z.number() }),
    );
  }
  async anchorHide(): Promise<void> {
    await call('anchor_hide', () => commands.anchorHide());
  }
  async anchorShow(): Promise<void> {
    await call('anchor_show', () => commands.anchorShow());
  }
  async anchorMenuPopup(): Promise<void> {
    await call('anchor_menu_popup', () => commands.anchorMenuPopup());
  }
  async anchorSetExpanded(expanded: boolean): Promise<void> {
    await call('anchor_set_expanded', () => commands.anchorSetExpanded({ expanded }));
  }
  dockOpenSettings(): Promise<void> {
    return call('dock_open_settings', () => commands.dockOpenSettings());
  }
  async pauseSet(untilEpochMs: number | null): Promise<void> {
    await call('pause_set', () => commands.pauseSet({ untilEpochMs }));
  }
  appQuit(): Promise<void> {
    return call('app_quit', () => commands.appQuit());
  }

  authSignIn(): Promise<Session> {
    return call('auth_sign_in', () => commands.authSignIn(), Session);
  }
  async authSignOut(): Promise<void> {
    await call('auth_sign_out', () => commands.authSignOut());
  }
  authGetSession(): Promise<Session> {
    return call('auth_get_session', () => commands.authGetSession(), Session);
  }

  askSubmit(req: AskSubmitRequest): Promise<AskSubmitResult> {
    return call('ask_submit', () => commands.askSubmit(req), AskSubmitResult);
  }
  async askCancel(taskId: string): Promise<void> {
    await call('ask_cancel', () => commands.askCancel({ taskId }));
  }
  attentionList(): Promise<AttentionItem[]> {
    return call('attention_list', () => commands.attentionList(), z.array(AttentionItem));
  }
  attentionDecide(decision: AttentionDecision): Promise<AttentionDecideResult> {
    return call('attention_decide', () => commands.attentionDecide(decision), AttentionDecideResult);
  }
  ledgerQuery(query: LedgerQuery): Promise<LedgerPage> {
    return call('ledger_query', () => commands.ledgerQuery(query), LedgerPage);
  }
  journeyGet(journeyId: string): Promise<JourneyThread> {
    return call('journey_get', () => commands.journeyGet({ journeyId }), JourneyThread);
  }

  settingsGet(): Promise<Settings> {
    return call('settings_get', () => commands.settingsGet(), Settings);
  }
  settingsSet(settings: Settings): Promise<Settings> {
    return call('settings_set', () => commands.settingsSet(settings), Settings);
  }
  monitorsList(): Promise<MonitorInfo[]> {
    return call('monitors_list', () => commands.monitorsList(), z.array(MonitorInfo));
  }
  async openExternal(url: string): Promise<void> {
    await call('open_external', () => commands.openExternal({ url }));
  }
  telemetryEvent(name: string, props?: Record<string, unknown>): Promise<void> {
    return call('telemetry_event', () => commands.telemetryEvent({ name, props: props ?? {} }));
  }

  on: LoopAdapter['on'] = (event, handler) => this.hub.on(event, handler);
}
