import { z } from 'zod';
import { RecordCard } from './cards/record';
import { AgentId, DecisionOption, Evidence, IsoDateTime, Person, Platform, Uuid } from './common';

/**
 * `confirm`  approve / reject a proposal
 * `choose`   pick between options (clarifying question, disambiguation)
 * `provide`  free-text answer to an agent's question
 * `auth`     sign in again or consent; single primary action opens the browser
 */
export const AttentionKind = z.enum(['confirm', 'choose', 'provide', 'auth']);
export type AttentionKind = z.infer<typeof AttentionKind>;

export const AttentionState = z.enum(['open', 'decided', 'expired']);
export type AttentionState = z.infer<typeof AttentionState>;

export const AttentionItem = z.object({
  attentionId: Uuid,
  journeyId: Uuid,
  taskId: z.string().optional(),
  kind: AttentionKind,
  title: z.string().min(1),
  requester: Person,
  subject: z.string().min(1),
  department: z.string().optional(),
  agentId: AgentId,
  platform: Platform,
  evidence: z.array(Evidence).max(8).default([]),
  /** 2-3 options; `auth` items carry exactly one. */
  options: z.array(DecisionOption).min(1).max(3),
  allowFreeText: z.boolean().default(true),
  record: RecordCard.optional(),
  createdAt: IsoDateTime,
  expiresAt: IsoDateTime,
  state: AttentionState.default('open'),
  decision: z
    .object({
      optionId: z.string(),
      decidedAt: IsoDateTime,
      by: Person,
    })
    .optional(),
});
export type AttentionItem = z.infer<typeof AttentionItem>;

/**
 * A decision on an Attention item or an inline `choice` / `confirmation` card.
 * `decision` is an `optionId` or the literal `'reject'`.
 * `idempotencyKey` is generated by the UI once per attempt and reused on retry.
 */
export const AttentionDecision = z.strictObject({
  attentionId: Uuid,
  decision: z.string().min(1),
  freeText: z.string().max(2000).optional(),
  decidedAt: IsoDateTime,
  idempotencyKey: Uuid,
});
export type AttentionDecision = z.infer<typeof AttentionDecision>;

export const AttentionDecideResult = z.object({
  accepted: z.boolean(),
});
export type AttentionDecideResult = z.infer<typeof AttentionDecideResult>;
